# Sponsorluk ve Destek

# GitHub Sponsors (aktif olduğunda)
# github: [meertseker]

# Patreon (kullanıyorsanız)
# patreon: sekersoft

# Open Collective (kullanıyorsanız)
# open_collective: sekersoft

# Ko-fi (kullanıyorsanız)
# ko_fi: sekersoft

# Buy Me a Coffee (kullanıyorsanız)
# custom: ["https://www.buymeacoffee.com/sekersoft"]

# Özel bağış linkleri
custom: ["https://seymentransport.com/destek"]

